points:
  floor_1:
    home_point_1: 
      x: 0.0
      y: 0.0
      z_orient: 0.0
      w_orient: 0.0
    elevator1:
      x: 3.0
      y: 0.0
      z_orient: 0.0
      w_orient: 0.0
  floor_2:
    home_point_2:
      x: 0.0
      y: 0.0
      z_orient: 0.0
      w_orient: 0.0
    elevaotr2:
      x: 1.5
      y: 1.0
      z_orient: 0.0
      w_orient: 0.0
  floor_3:
    home_point_3:
      x: 0.0
      y: 0.0
      z_orient: 0.0
      w_orient: 0.0
    elevator3:
      x: 1.5
      y: 1.0
      z_orient: 0.0
      w_orient: 0.0